_sourcetests: fetch missing after tracking
Over in: https://gitlab.com/BuildStream/buildstream-plugins-community/-/merge_requests/484
We hit: FAILED
`buildstream/_testing/_sourcetests/track.py::test_cross_junction[git_repo-project.refs] -
AssertionError: assert 'fetch needed' == 'buildable'`

Looking at the other tests in this file,
all except this one have the '# And now fetch it:` comment and call a call to bst fetch.

It looks like it's missing in this test.

As `git_repo` does not cache it's sources as part of track.